# Generated by Django 3.1.7 on 2021-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('region', models.CharField(choices=[('O', 'OSH'), ('T', 'TALAS'), ('C', 'CHUI'), ('B', 'BATKEN'), ('I', 'ISSYK-KUL'), ('N', 'NARYN'), ('J', 'JALAL-ABAD')], max_length=1)),
                ('gos', models.BooleanField(default=True)),
            ],
        ),
    ]
