# Generated by Django 3.1.7 on 2021-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210403_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='person',
            field=models.CharField(default=10, max_length=2),
        ),
    ]
